development:
  braintree:
    environment: :sandbox
    merchant_id: 'nmgrjk6vkbzm594w'
    master_merchant_account_id: 'cwcskh2zdt64msmh'

test:
  braintree:
    environment: :sandbox
    merchant_id: 'nmgrjk6vkbzm594w'
    master_merchant_account_id: 'cwcskh2zdt64msmh'

staging:
  braintree:
    environment: :sandbox
    merchant_id: 'nmgrjk6vkbzm594w'
    master_merchant_account_id: 'cwcskh2zdt64msmh'

production:
  braintree:
    environment: :production
    merchant_id: 'idontknow'
    master_merchant_account_id: 'cwcskh2zdt64msmh'
