# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b432545d32e76bf64a718ee6d2bd266cc71315978f364ae07638508ca1049bbf548cdb6881df6e9e36d37aef1a6f8585b40a7d0ce78592a770361a8cbf0ab0a6
  braintree_environment: :sandbox
  braintree_merchant_id: nmgrjk6vkbzm594w
  braintree_master_merchant_account_id: cwcskh2zdt64msmh
  braintree_public_key: cn2xmrngfgv34xqg
  braintree_private_key: 8bdb00856cec6c05caf41a04a541e8b2
  braintree_cse:  MIIBCgKCAQEAmmbTYAQ1XHFblsCGb00pq+S9/uuyYUkIaOut774GI+1OEYqQSCuziL0crBCqcmwicVGamWFOsgfw301WDMtlqrQruooWp9kpdOW/M5Llgygbj9FoGE8hNWU8ffC6YvUX/ooVJwItuFyLqRhUaHp3wJeN4f+ZWLapivoTNqHeZaT6AXFpee1eyySsVO3AUSLybUfCeJRLaRJmPVC6wpjkBO6WrKQJIFHU6slR6UU/pdNoHhJ4+jdW/xpi1MxI+oPhz8X+iZMli+UU5qdkAWa0+vrxHvLOEdeVCk2m87slspsgD0ppgOoFUthzPDSjFzFX9aflFkKhqfjsPj7+zmKDLQIDAQAB
  twilio_phone_number: 3126971632
  twilio_account_sid: AC66f3c0fd1967fb3797500519370c0a0a
  twilio_auth_token: cb1c557801a65339cd4fa7b482784ebc
  sendgrid_api_user: sittercitymarketplace
  sendgrid_api_key: j0alasdfA856cec6c05cayAcy_4sBqhLw
  sendgrid_from_address: support@sittercity.com
  google_api_key: AIzaSyAcy_4sBqhLwku25GFfDHcaFUVh7FMe0vA
  
test:
  secret_key_base: 31cebd5e6fa4f860f12fb10aa974d2ddce499e6c98a37fd705028faa06b295356a05ead83b1f00da8677fbe04b60a72ce7bf0ec82dda31daf26b06f513bd3514
  braintree_environment: :sandbox
  braintree_merchant_id: nmgrjk6vkbzm594w
  braintree_master_merchant_account_id: cwcskh2zdt64msmh
  braintree_public_key: cn2xmrngfgv34xqg
  braintree_private_key: 8bdb00856cec6c05caf41a04a541e8b2
  braintree_cse:  MIIBCgKCAQEAmmbTYAQ1XHFblsCGb00pq+S9/uuyYUkIaOut774GI+1OEYqQSCuziL0crBCqcmwicVGamWFOsgfw301WDMtlqrQruooWp9kpdOW/M5Llgygbj9FoGE8hNWU8ffC6YvUX/ooVJwItuFyLqRhUaHp3wJeN4f+ZWLapivoTNqHeZaT6AXFpee1eyySsVO3AUSLybUfCeJRLaRJmPVC6wpjkBO6WrKQJIFHU6slR6UU/pdNoHhJ4+jdW/xpi1MxI+oPhz8X+iZMli+UU5qdkAWa0+vrxHvLOEdeVCk2m87slspsgD0ppgOoFUthzPDSjFzFX9aflFkKhqfjsPj7+zmKDLQIDAQAB
  twilio_phone_number: 3126971632
  twilio_account_sid: AC66f3c0fd1967fb3797500519370c0a0a
  twilio_auth_token: cb1c557801a65339cd4fa7b482784ebc
  sendgrid_api_user: sittercitymarketplace
  sendgrid_api_key: j0alasdfA856cec6c05cayAcy_4sBqhLw
  sendgrid_from_address: support@sittercity.com
  google_api_key: AIzaSyAcy_4sBqhLwku25GFfDHcaFUVh7FMe0vA

staging:
  secret_key_base: 31cebd5e6fa4f860f12fb10aa974d2ddce499e6c98a37fd705028faa06b295356a05ead83b1f00da8677fbe04b60a72ce7bf0ec82dda31daf26b06f513bd3514
  braintree_environment: :sandbox
  braintree_merchant_id: nmgrjk6vkbzm594w
  braintree_master_merchant_account_id: cwcskh2zdt64msmh
  braintree_public_key: cn2xmrngfgv34xqg
  braintree_private_key: 8bdb00856cec6c05caf41a04a541e8b2
  braintree_cse:  MIIBCgKCAQEAmmbTYAQ1XHFblsCGb00pq+S9/uuyYUkIaOut774GI+1OEYqQSCuziL0crBCqcmwicVGamWFOsgfw301WDMtlqrQruooWp9kpdOW/M5Llgygbj9FoGE8hNWU8ffC6YvUX/ooVJwItuFyLqRhUaHp3wJeN4f+ZWLapivoTNqHeZaT6AXFpee1eyySsVO3AUSLybUfCeJRLaRJmPVC6wpjkBO6WrKQJIFHU6slR6UU/pdNoHhJ4+jdW/xpi1MxI+oPhz8X+iZMli+UU5qdkAWa0+vrxHvLOEdeVCk2m87slspsgD0ppgOoFUthzPDSjFzFX9aflFkKhqfjsPj7+zmKDLQIDAQAB
  twilio_phone_number: 3126971632
  twilio_account_sid: AC66f3c0fd1967fb3797500519370c0a0a
  twilio_auth_token: cb1c557801a65339cd4fa7b482784ebc
  sendgrid_api_user: sittercitymarketplace
  sendgrid_api_key: j0alasdfA856cec6c05cayAcy_4sBqhLw
  sendgrid_from_address: support@sittercity.com
  google_api_key: AIzaSyAcy_4sBqhLwku25GFfDHcaFUVh7FMe0vA

#TODO: (AC 2014Jun17) - NEED TO REMOVE FROM GIT AND LOAD FROM ENVIRONMENT

production:
  secret_key_base: 31b432545d32e76bf64a718ee6d4d2ddce499e6c98a37fd705028faa06b295356a05ea8508ca1049bbf54be04b60a72ce7bf0ec82dda31daf26b06f513bd3514
  braintree_environment: :sandbox
  braintree_merchant_id: nmgrjk6vkbzm594w
  braintree_master_merchant_account_id: cwcskh2zdt64msmh
  braintree_public_key: cn2xmrngfgv34xqg
  braintree_private_key: 8bdb00856cec6c05caf41a04a541e8b2
  braintree_cse:  MIIBCgKCAQEAmmbTYAQ1XHFblsCGb00pq+S9/uuyYUkIaOut774GI+1OEYqQSCuziL0crBCqcmwicVGamWFOsgfw301WDMtlqrQruooWp9kpdOW/M5Llgygbj9FoGE8hNWU8ffC6YvUX/ooVJwItuFyLqRhUaHp3wJeN4f+ZWLapivoTNqHeZaT6AXFpee1eyySsVO3AUSLybUfCeJRLaRJmPVC6wpjkBO6WrKQJIFHU6slR6UU/pdNoHhJ4+jdW/xpi1MxI+oPhz8X+iZMli+UU5qdkAWa0+vrxHvLOEdeVCk2m87slspsgD0ppgOoFUthzPDSjFzFX9aflFkKhqfjsPj7+zmKDLQIDAQAB
  twilio_phone_number: 3126971632
  twilio_account_sid: AC66f3c0fd1967fb3797500519370c0a0a
  twilio_auth_token: cb1c557801a65339cd4fa7b482784ebc
  sendgrid_api_user: sittercitymarketplace
  sendgrid_api_key: j0alasdfA856cec6c05cayAcy_4sBqhLw
  sendgrid_from_address: support@sittercity.com
  google_api_key: AIzaSyAcy_4sBqhLwku25GFfDHcaFUVh7FMe0vA
